export const cardData = [
    {"Title":"I of Pentacles","Suit":"Pentacles","Ordinal":1,"OrdinalName":"I"},
    {"Title":"II of Pentacles","Suit":"Pentacles","Ordinal":2,"OrdinalName":"II"},
    {"Title":"III of Pentacles","Suit":"Pentacles","Ordinal":3,"OrdinalName":"III"},
    {"Title":"IV of Pentacles","Suit":"Pentacles","Ordinal":4,"OrdinalName":"IV"},
    {"Title":"V of Pentacles","Suit":"Pentacles","Ordinal":5,"OrdinalName":"V"},
    {"Title":"VI of Pentacles","Suit":"Pentacles","Ordinal":6,"OrdinalName":"VI"},
    {"Title":"VII of Pentacles","Suit":"Pentacles","Ordinal":7,"OrdinalName":"VII"},
    {"Title":"VIII of Pentacles","Suit":"Pentacles","Ordinal":8,"OrdinalName":"VIII"},
    {"Title":"IX of Pentacles","Suit":"Pentacles","Ordinal":9,"OrdinalName":"IX"},
    {"Title":"X of Pentacles","Suit":"Pentacles","Ordinal":10,"OrdinalName":"X"},
    {"Title":"Page of Pentacles","Suit":"Pentacles","Ordinal":11,"OrdinalName":"Page"},
    {"Title":"Knight of Pentacles","Suit":"Pentacles","Ordinal":12,"OrdinalName":"Knight"},
    {"Title":"Queen of Pentacles","Suit":"Pentacles","Ordinal":13,"OrdinalName":"Queen"},
    {"Title":"King of Pentacles","Suit":"Pentacles","Ordinal":14,"OrdinalName":"King"},
    {"Title":"I of Cups","Suit":"Cups","Ordinal":1,"OrdinalName":"I"},
    {"Title":"II of Cups","Suit":"Cups","Ordinal":2,"OrdinalName":"II"},
    {"Title":"III of Cups","Suit":"Cups","Ordinal":3,"OrdinalName":"III"},
    {"Title":"IV of Cups","Suit":"Cups","Ordinal":4,"OrdinalName":"IV"},
    {"Title":"V of Cups","Suit":"Cups","Ordinal":5,"OrdinalName":"V"},
    {"Title":"VI of Cups","Suit":"Cups","Ordinal":6,"OrdinalName":"VI"},
    {"Title":"VII of Cups","Suit":"Cups","Ordinal":7,"OrdinalName":"VII"},
    {"Title":"VIII of Cups","Suit":"Cups","Ordinal":8,"OrdinalName":"VIII"},
    {"Title":"IX of Cups","Suit":"Cups","Ordinal":9,"OrdinalName":"IX"},
    {"Title":"X of Cups","Suit":"Cups","Ordinal":10,"OrdinalName":"X"},
    {"Title":"Page of Cups","Suit":"Cups","Ordinal":11,"OrdinalName":"Page"},
    {"Title":"Knight of Cups","Suit":"Cups","Ordinal":12,"OrdinalName":"Knight"},
    {"Title":"Queen of Cups","Suit":"Cups","Ordinal":13,"OrdinalName":"Queen"},
    {"Title":"King of Cups","Suit":"Cups","Ordinal":14,"OrdinalName":"King"},
    {"Title":"I of Wands","Suit":"Wands","Ordinal":1,"OrdinalName":"I"},
    {"Title":"II of Wands","Suit":"Wands","Ordinal":2,"OrdinalName":"II"},
    {"Title":"III of Wands","Suit":"Wands","Ordinal":3,"OrdinalName":"III"},
    {"Title":"IV of Wands","Suit":"Wands","Ordinal":4,"OrdinalName":"IV"},
    {"Title":"V of Wands","Suit":"Wands","Ordinal":5,"OrdinalName":"V"},
    {"Title":"VI of Wands","Suit":"Wands","Ordinal":6,"OrdinalName":"VI"},
    {"Title":"VII of Wands","Suit":"Wands","Ordinal":7,"OrdinalName":"VII"},
    {"Title":"VIII of Wands","Suit":"Wands","Ordinal":8,"OrdinalName":"VIII"},
    {"Title":"IX of Wands","Suit":"Wands","Ordinal":9,"OrdinalName":"IX"},
    {"Title":"X of Wands","Suit":"Wands","Ordinal":10,"OrdinalName":"X"},
    {"Title":"Page of Wands","Suit":"Wands","Ordinal":11,"OrdinalName":"Page"},
    {"Title":"Knight of Wands","Suit":"Wands","Ordinal":12,"OrdinalName":"Knight"},
    {"Title":"Queen of Wands","Suit":"Wands","Ordinal":13,"OrdinalName":"Queen"},
    {"Title":"King of Wands","Suit":"Wands","Ordinal":14,"OrdinalName":"King"},
    {"Title":"I of Swords","Suit":"Swords","Ordinal":1,"OrdinalName":"I"},
    {"Title":"II of Swords","Suit":"Swords","Ordinal":2,"OrdinalName":"II"},
    {"Title":"III of Swords","Suit":"Swords","Ordinal":3,"OrdinalName":"III"},
    {"Title":"IV of Swords","Suit":"Swords","Ordinal":4,"OrdinalName":"IV"},
    {"Title":"V of Swords","Suit":"Swords","Ordinal":5,"OrdinalName":"V"},
    {"Title":"VI of Swords","Suit":"Swords","Ordinal":6,"OrdinalName":"VI"},
    {"Title":"VII of Swords","Suit":"Swords","Ordinal":7,"OrdinalName":"VII"},
    {"Title":"VIII of Swords","Suit":"Swords","Ordinal":8,"OrdinalName":"VIII"},
    {"Title":"IX of Swords","Suit":"Swords","Ordinal":9,"OrdinalName":"IX"},
    {"Title":"X of Swords","Suit":"Swords","Ordinal":10,"OrdinalName":"X"},
    {"Title":"Page of Swords","Suit":"Swords","Ordinal":11,"OrdinalName":"Page"},
    {"Title":"Knight of Swords","Suit":"Swords","Ordinal":12,"OrdinalName":"Knight"},
    {"Title":"Queen of Swords","Suit":"Swords","Ordinal":13,"OrdinalName":"Queen"},
    {"Title":"King of Swords","Suit":"Swords","Ordinal":14,"OrdinalName":"King"},
    {"Title":"0 of Trumps: \u2018The Fool\u2019","Suit":"Trumps","Ordinal":0,"OrdinalName":"0 (The Fool)"},
    {"Title":"I of Trumps: \u2018The Magician\u2019","Suit":"Trumps","Ordinal":1,"OrdinalName":"I (The Magician)"},
    {"Title":"II of Trumps: \u2018The High Priestess\u2019","Suit":"Trumps","Ordinal":2,"OrdinalName":"II (The High Priestess)"},
    {"Title":"III of Trumps: \u2018The Empress\u2019","Suit":"Trumps","Ordinal":3,"OrdinalName":"III (The Empress)"},
    {"Title":"IV of Trumps: \u2018The Emperor\u2019","Suit":"Trumps","Ordinal":4,"OrdinalName":"IV (The Emperor)"},
    {"Title":"V of Trumps: \u2018The Hierophant\u2019","Suit":"Trumps","Ordinal":5,"OrdinalName":"V (The Hierophant)"},
    {"Title":"VI of Trumps: \u2018The Lovers\u2019","Suit":"Trumps","Ordinal":6,"OrdinalName":"VI (The Lovers)"},
    {"Title":"VII of Trumps: \u2018The Chariot\u2019","Suit":"Trumps","Ordinal":7,"OrdinalName":"VII (The Chariot)"},
    {"Title":"VIII of Trumps: \u2018Strength\u2019","Suit":"Trumps","Ordinal":8,"OrdinalName":"VIII (Strength)"},
    {"Title":"IX of Trumps: \u2018The Hermit\u2019","Suit":"Trumps","Ordinal":9,"OrdinalName":"IX (The Hermit)"},
    {"Title":"X of Trumps: \u2018Wheel of Fortune\u2019","Suit":"Trumps","Ordinal":10,"OrdinalName":"X (Wheel of Fortune)"},
    {"Title":"XI of Trumps: \u2018Justice\u2019","Suit":"Trumps","Ordinal":11,"OrdinalName":"XI (Justice)"},
    {"Title":"XII of Trumps: \u2018The Hanged Man\u2019","Suit":"Trumps","Ordinal":12,"OrdinalName":"XII (The Hanged Man)"},
    {"Title":"XII of Trumps: \u2018Death\u2019","Suit":"Trumps","Ordinal":13,"OrdinalName":"XII (Death)"},
    {"Title":"XIV of Trumps: \u2018Temperance\u2019","Suit":"Trumps","Ordinal":14,"OrdinalName":"XIV (Temperance)"},
    {"Title":"XV of Trumps: \u2018The Devil\u2019","Suit":"Trumps","Ordinal":15,"OrdinalName":"XV (The Devil)"},
    {"Title":"XVI of Trumps: \u2018The Tower\u2019","Suit":"Trumps","Ordinal":16,"OrdinalName":"XVI (The Tower)"},
    {"Title":"XVII of Trumps: \u2018The Star\u2019","Suit":"Trumps","Ordinal":17,"OrdinalName":"XVII (The Star)"},
    {"Title":"XVIII of Trumps: \u2018The Moon\u2019","Suit":"Trumps","Ordinal":18,"OrdinalName":"XVIII (The Moon)"},
    {"Title":"XIX of Trumps: \u2018The Sun\u2019","Suit":"Trumps","Ordinal":19,"OrdinalName":"XIX (The Sun)"},
    {"Title":"XX of Trumps: \u2018Judgement\u2019","Suit":"Trumps","Ordinal":20,"OrdinalName":"XX (Judgement)"},
    {"Title":"XXI of Trumps: \u2018The World\u2019","Suit":"Trumps","Ordinal":21,"OrdinalName":"XXI (The World)"}       
];