export const cardData = [
    {
        "Id": 1,
        "Title": "Ace of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 1,
        "OrdinalName": "Ace",
		"GenderedCard": "Non-specific",
        "Normal": "The most favourable of all cards; perfect contentment, felicity, ecstasy; also speedy intelligence; gold",
        "Reversed": "The evil side of wealth, bad intelligence; also great riches, a share in the finding of treasure.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg",
        "Description":"A hand&#8212;issuing, as usual, from a cloud&#8212;holds up a pentacle. "
    },
    {
        "Id": 2,
        "Title": "II of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 2,
        "OrdinalName": "II",
        "GenderedCard": "Non-specific",
        "Normal": "On of the one hand it is represented as a card of gaiety, recreation and its connections, which is the subject of the design; but it is read also as news and messages in writing, as obstacles, agitation, trouble, embroilment.  Another reading indicates that troubles are more imaginary than real.",
        "Reversed": "Enforced gaiety, simulated enjoyment, literal sense, handwriting, composition, letters of exchange.  Also bad omen, ignorance, injustice.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg",
        "Description":"A young man, in the act of dancing, has a pentacle in either hand, and they are joined by that endless cord which is like the infinite symbol, a number 8 reversed, or a Möbius band."
    },
    {
        "Id": 3,
        "Title": "III of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 3,
        "OrdinalName": "III",
        "GenderedCard": "Non-specific",
        "Normal": "Vocation, trade, skilled labour; usually, however, regarded as a card of nobility, aristocracy, renown, glory.  If for a man, celebrity for his eldest son.",
        "Reversed": "Mediocrity in work and otherwise, puerility, pettiness, weakness.  Interpretation depends on the neighbouring cards.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg",
        "Description":"A sculptor at his work in a monastery. Compare the design which illustrates the Eight of Pentacles. The apprentice or amateur therein has received his reward and is now at work in earnest."
    },
    {
        "Id": 4,
        "Title": "IV of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 4,
        "OrdinalName": "IV",
        "GenderedCard": "Male",
        "Normal": "The surety of possession, cleaving to that which one has, gifts, legacy, inheritance.  For a bachelor, pleasant news from a lady.",
        "Reversed": "Suspense, delay, opposition.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg",
        "Description":"A crowned figure, having a pentacle over his crown, clasps another with hands and arms; two pentacles are under his feet. He holds to that which he has. "
    },
    {
        "Id": 5,
        "Title": "V of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 5,
        "OrdinalName": "V",
        "GenderedCard": "Non-specific",
        "Normal": "This card foretells material trouble above all, whether in the form illustrated - that is, destitution - or otherwise. For some cartomancists, it is a card  of love and lovers - wife, husband, friend, mistress; also concordance, affinities. These alternatives cannot be harmonised.",
        "Reversed": "Disorder, chaos, ruin, discord, profligacy, troubles in love.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg",
        "Description":"Two mendicants in a snow-storm pass a lighted casement. "
    },
    {
        "Id": 6,
        "Title": "VI of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 6,
        "OrdinalName": "VI",
		"GenderedCard": "Male",
        "Normal": "Work, employment, commission, craftsmanship, skill in craft and business. A young man in business who has relations with the Querent; a dark girl.",
        "Reversed": "Voided ambition, vanity, cupidity, exaction, usury. Another reading indicates that the Querent will be compromised in a matter of money lending.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg",
        "Description":"A person in the guise of a merchant weighs money in a pair of scales and distributes it to the needy and distressed. It is a testimony to his own success in life, as well as to his goodness of heart. "
    },
    {
        "Id": 7,
        "Title": "VII of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 7,
        "OrdinalName": "VII",
        "GenderedCard": "Non-specific",
        "Normal": "These are exeedingly contradictory: in the main, it is a card of money, business, barter; but one reading gives altercation, quarrel; and another innocence, ingenuity, purgation. Also an improved position for a lady’s future husband.",
        "Reversed": "The readings are too vague and contradictory to provide a reliable divination.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg",
        "Description":"A young man, leaning on his staff, looks intently at seven pentacles attached to a clump of greenery on his right; one would say that these were his treasures and that his heart was there. "
    },
    {
        "Id": 8,
        "Title": "VIII of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 8,
        "OrdinalName": "VIII",
		"GenderedCard": "Non-specific",
        "Normal": "Work, employment, commission, craftsmanship, skill in craft and business. A young man in business who has relations with the Querent; a dark girl.",
        "Reversed": "Voided ambition, vanity, cupidity, exaction, usury. Another reading indicates that the Querent will be compromised in a matter of money lending.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg",
        "Description":"An artist in stone at his work, which he exhibits in the form of trophies."
    },
    {
        "Id": 9,
        "Title": "IX of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 9,
        "OrdinalName": "IX",
        "GenderedCard": "Non-specific",
        "Normal": "Prudence, safety, success, accomplishment, certitude, discernment; prompt fulfilment of what is presaged by neighbouring plants cards.",
        "Reversed": "Roguery, deception, voided project, bad faith.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg",
        "Description":"A woman, with a bird upon her wrist, stands amidst a great abundance of grapevines in the garden of a manorial house. It is a wide domain, suggesting plenty in all things. Possibly it is her own possession and testifies to material well-being. "
    },
    {
        "Id": 10,
        "Title": "X of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 10,
        "OrdinalName": "X",
        "GenderedCard": "Non-specific",
        "Normal": "Gain, riches; family matters, archives, extraction. This card can represent a house or dwelling, the abode of a family, and derives its value from other cards.",
        "Reversed": "Chance, fatality, loss, robbery, games of hazard; sometimes gift, dowry, pension.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg",
        "Description":"A man and woman beneath an archway which gives entrance to a house and domain. They are accompanied by a child, who looks curiously at two dogs accosting an ancient personage seated in the foreground. The child\u2019s hand is on one of them. "
    },
    {
        "Id": 11,
        "Title": "Page of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 11,
        "OrdinalName": "Page",
        "GenderedCard": "Male",
        "Normal": "A dark youth; a young officer or soldier; a child.  Application, study, scholarship, reflection; another reading says news, messages and the bringer of these; also rule, management.",
        "Reversed": "Prodigality, dissipation, liberality, luxury; unfavourable news.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg",
        "Description":"A youthful figure, looking intently at the pentacle which hovers over his raised hands. He moves slowly, insensible of that which is about him. "
    },
    {
        "Id": 12,
        "Title": "Knight of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 12,
        "OrdinalName": "Knight",
        "GenderedCard": "Male",
        "Normal": "Utility, serviceableness, interest, responsibility, rectitude; a useful man, useful discoveries.",
        "Reversed": "Inertia, idleness, repose of that kind, stagnation; also placidity, discouragement, carelessness; a brave man out of employment.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg",
        "Description":"He rides a slow, enduring, heavy horse, to which his own aspect corresponds. He exhibits his symbol, but does not look therein. "
    },
    {
        "Id": 13,
        "Title": "Queen of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 13,
        "OrdinalName": "Queen",
		"Gendered":true,
        "GenderedCard": "Female",
        "Normal": "Opulence, generosity, magnificence, security, liberty.  A dark woman; presents from a rich relative; rich and happy marriage for a young man.",
        "Reversed": "Evil, suspicion, suspense, fear, mistrust, illness.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg",
        "Description":"The face suggests that of a dark woman, whose qualities might be summed up in the idea of greatness of soul; she has also the serious cast of intelligence; she contemplates her symbol and may see worlds therein. "
    },
    {
        "Id": 14,
        "Title": "King of Pentacles",
        "Suit": "Pentacles",
        "Ordinal": 14,
        "OrdinalName": "King",
        "GenderedCard": "Male",
        "Normal": "A rather dark man, a merchant, master, professor. Valour, realising intelligence, business and normal intellectual aptitude, sometimes mathematical gifts and attainments of this kind; success in these paths.",
        "Reversed": "And old and vicious man; vice, weakness, ugliness, perversity, corruption, peril.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg",
        "Description":"The figure calls for no special description the face is rather dark, suggesting also courage, but somewhat lethargic in tendency. The bull\u2019s head should be noted as a recurrent symbol on the throne. The sign of this suit is represented throughout as engraved or blazoned with the pentagram, typifying the correspondence of the four elements in human nature and that by which they may be governed. In many old Tarot packs this suit stood for current coin, money, deniers. I have not invented the substitution of pentacles and I have no special cause to sustain in respect of the alternative. But the consensus of divinatory meanings is on the side of some change, because the cards do not happen to deal especially with questions of money. "
    },
    {
        "Id": 15,
        "Title": "Ace of Cups",
        "Suit": "Cups",
        "Ordinal": 1,
        "OrdinalName": "Ace",
        "GenderedCard": "Non-specific",
        "Normal": "House of the true heart, joy, content, abode, nourishment, abundance, fertility, holy table, happiness.  Also inflexible will, unalterable law.",
        "Reversed": "Houe of the false heart, mutation, instability, revolution.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg",
        "Description":"The waters are beneath, and thereon are water-lilies; the hand issues from the cloud, holding in its palm the cup, from which four streams are pouring; a dove, bearing in its bill a cross-marked Host, descends to place the Wafer in the Cup; the dew of water is falling on all sides. It is an intimation of that which may lie behind the Lesser Arcana. "
    },
    {
        "Id": 16,
        "Title": "II of Cups",
        "Suit": "Cups",
        "Ordinal": 2,
        "OrdinalName": "II",
        "GenderedCard": "Non-specific",
        "Normal": "Love, passion, friendship, affinity, union, concord, sympathy, the interrelation of the sexes, and - as a suggestion apart from all offices of divination - that desire which is not in nature, and by which nature is sanctified.  Favourable in things of pleasure and business as well as love.",
        "Reversed": "There are readings for this card in the reversed position, but in a language unknown.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg",
        "Description":"A youth and maiden are pledging one another, and above their cups rises the Caduceus of Hermes, between the great wings of which there appears a lion\u2019s head. It is a variant of a sign which is found in a few old examples of this card. Some curious emblematical meanings are attached to it, but they do not concern us in this place. "
    },
    {
        "Id": 17,
        "Title": "III of Cups",
        "Suit": "Cups",
        "Ordinal": 3,
        "OrdinalName": "III",
		"Gendered":true,
        "GenderedCard": "Non-specific",
        "Normal": "The conclusion of any matter in plenty, perfection and merriment; happy outcome, victory, fulfilment, solace, healing; unexpected advancement for a military man.",
        "Reversed": "Expedition, despatch, achievement, end, consolation.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg",
        "Description":"Maidens in a garden-ground with cups uplifted, as if pledging one another. "
    },
    {
        "Id": 18,
        "Title": "IV of Cups",
        "Suit": "Cups",
        "Ordinal": 4,
        "OrdinalName": "IV",
        "GenderedCard": "Non-specific",
        "Normal": "Weariness, disgust, aversion, imaginary vexations, as if the wine of this world had caused satiety only; another wine, as if a fairy gift, is now offered to the young man on the card, but he sees no consolation in this.  This is also a kind of blended pleasure, Contrarieties.",
        "Reversed": "Novelty, presage, new instruction, new relations.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg",
        "Description":"A young man is seated under a tree and contemplates three cups set on the grass before him; an arm issuing from a cloud offers him another cup. His expression notwithstanding is one of discontent with his environment. "
    },
    {
        "Id": 19,
        "Title": "V of Cups",
        "Suit": "Cups",
        "Ordinal": 5,
        "OrdinalName": "V",
        "GenderedCard": "Non-specific",
        "Normal": "It is a card of loss, but something remains over; three cups have been taken but two are left; it is a card of inheritance, patrimony, transmission, but not corresponding to expectations; with some it is a card of marriage, but not without bitterness or frustration.  Other meanings are generally favourable, indicating a happy marriage, for instance.",
        "Reversed": "News, alliances, affinity, consanguinity, ancestry, false projects; return - for example, of some relative who has not been seen for a long time.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg",
        "Description":"A dark, cloaked figure, looking sideways at three prone cups two others stand upright behind him; a bridge is in the background, leading to a small keep or holding. "
    },
    {
        "Id": 20,
        "Title": "VI of Cups",
        "Suit": "Cups",
        "Ordinal": 6,
        "OrdinalName": "VI",
        "GenderedCard": "Non-specific",
        "Normal": "A card of the past and of memories, looking back, as - for example - on childhood; happiness, enjoyment, but coming rather from the past; things that have vanished; pleasant memories.  Another reading reverses this, giving new relations, new knowledge, new environment, and then the children are playing in a newly entered precinct.",
        "Reversed": "The future, renewal, that which will come to pass presently.  Also inheritance to fall in quickly.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg",
        "Description":"Children in an old garden, their cups filled with flowers. "
    },
    {
        "Id": 21,
        "Title": "VII of Cups",
        "Suit": "Cups",
        "Ordinal": 7,
        "OrdinalName": "VII",
        "GenderedCard": "Non-specific",
        "Normal": "Fairy favours, images of reflection, sentiment, imagination, things seen in the glass of contemplation; some attainment in these degrees but nothing permanent or substantial is suggested.  Also: a fair child; idea, design, movement.",
        "Reversed": "Desire, will, determination, project.  Success, if accompanied by the Three of Cups.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg",
        "Description":"Strange chalices of vision, but the images are more especially those of the fantastic spirit."
    },
    {
        "Id": 22,
        "Title": "VIII of Cups",
        "Suit": "Cups",
        "Ordinal": 8,
        "OrdinalName": "VIII",
        "GenderedCard": "Non-specific",
        "Normal": "The card speaks for itself on the surface, but other readings are entirely antithetical, giving joy, mildness, timidity, honour, modesty, marriage with a fair woman.",
        "Reversed": "Great joy, happiness, feasting.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg",
        "Description":"A man of dejected aspect is deserting the cups of his felicity, enterprise, undertaking or previous concern. "
    },
    {
        "Id": 23,
        "Title": "IX of Cups",
        "Suit": "Cups",
        "Ordinal": 9,
        "OrdinalName": "IX",
        "GenderedCard": "Non-specific",
        "Normal": "Concord, contentment, physical well-being; also victory, success, advantage; of good augury for military men; satisfaction for the querent or person for whom the consultation is made.",
        "Reversed": "Truth loyalty, liberty, good business; but the readings vary and include mistakes and imperfections.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg",
        "Description":"A goodly personage has feasted to his heart’s content, and abundant refreshment of wine is on the arched counter behind him, seeming to indicate that the future is also assured. The picture offers the material side only, but there are other aspects."
    },
    {
        "Id": 24,
        "Title": "X of Cups",
        "Suit": "Cups",
        "Ordinal": 10,
        "OrdinalName": "X",
        "GenderedCard": "Non-specific",
        "Normal": "Contentment, repose of the entire heart; the perfection of that state; if with several picture cards, a person who’s taking charge of the querent’s interests; also the town, village or country inhabited by the  querent.  For a male querent, a good marriage and beyond his expectations.",
        "Reversed": "PRepose of the false heart, indignation, violence, sorrow.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg",
        "Description":"Appearance of Cups in a rainbow; it is contemplated in wonder and ecstacy by a man and woman below, evidently husband and wife. His right arm is about her; his left is raised upward; she raises her right arm. The two children dancing near them have not observed the prodigy but are happy after their own manner. There is a home-scene beyond."
    },
    {
        "Id": 25,
        "Title": "Page of Cups",
        "Suit": "Cups",
        "Ordinal": 11,
        "OrdinalName": "Page",
        "GenderedCard": "Male",
        "Normal": "For a young man, one impelled to render service and with whom the  querent will be connected; a studious youth; news, message, good augury; application, reflection, meditation; also these things directed to business.",
        "Reversed": "Taste, inclination, attachment, seduction, deception, artifice, obstacles of all kinds.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg",
        "Description":"A fair, pleasing, somewhat effeminate page, of studious and intent aspect, contemplates a fish rising from a cup to look at him. It is the pictures of the mind taking form. "
    },
    {
        "Id": 26,
        "Title": "Knight of Cups",
        "Suit": "Cups",
        "Ordinal": 12,
        "OrdinalName": "Knight",
        "GenderedCard": "Male",
        "Normal": "Arrival, approach - sometimes that of a messenger; a visit from a friend, who will bring unexpected money to the querent.  Also advances, proposition, demeanor, invitation, incitement.",
        "Reversed": "Trickery, artifice, subtlety, swindling, duplicity, fraud.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg",
        "Description":"Graceful, but not warlike; riding quietly, wearing a winged helmet, referring to those higher graces of the imagination which sometimes characterize this card. He too is a dreamer, but the images of the side of sense haunt him in his vision."
    },
    {
        "Id": 27,
        "Title": "Queen of Cups",
        "Suit": "Cups",
        "Ordinal": 13,
        "OrdinalName": "Queen",
        "GenderedCard": "Female",
        "Normal": "Good fair woman; honest, devoted woman, who will do service to the querent; loving intelligence, and hence the gift of vision; success happiness, pleasure; also wisdom, virtue.  Sometimes denotes woman of equivocal character.",
        "Reversed": "The accounts vary: good woman; otherwise distinguished woman but one not to be trusted; perverse woman; vice, dishonour, depravity; a rich marriage.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg",
        "Description":"Beautiful, fair, dreamy&#8212;as one who sees visions in a cup. This is, however, only one of her aspects; she sees, but she also acts, and her activity feeds her dream. "
    },
    {
        "Id": 28,
        "Title": "King of Cups",
        "Suit": "Cups",
        "Ordinal": 14,
        "OrdinalName": "King",
        "GenderedCard": "Male",
        "Normal": "Fair man, man of business, law or divinity; responsible, disposed to oblige the querent; also equity, art and science, including those who profess science, law and art; creative intelligence.  Beware of ill will on the part of a man of position.",
        "Reversed": "Dishonest, double-dealing man; roguery, exaction, injustice, vice, scandal, loss.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg",
        "Description":"He holds a short sceptre in his left hand and a great cup in his right; his throne is set upon the sea; on one side a ship is riding and on the other a dolphin is leaping. The implicit is that the Sign of the Cup naturally refers to water, which appears in all the court cards. "
    },
    {
        "Id": 29,
        "Title": "Ace of Wands",
        "Suit": "Wands",
        "Ordinal": 1,
        "OrdinalName": "Ace",
        "GenderedCard": "Non-specific",
        "Normal": "Creation, invention, enterprise, the powers which result in these; principle, beginning, source; birth, family, origin; the beginning of enterprises; according to another account, money, fortune, inheritance.  Another reading predicts calamities of all kinds.",
        "Reversed": "Fall, decadence, ruin, perdition, to perish; also - not unfounded joy.  A sign of birth.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg",
        "Description":"A hand issuing from a cloud grasps a stout wand or club."
    },
    {
        "Id": 30,
        "Title": "II of Wands",
        "Suit": "Wands",
        "Ordinal": 2,
        "OrdinalName": "II",
        "GenderedCard": "Non-specific",
        "Normal": "Between the alternate readings there is no marriage possible: on the one hand, riches, fortune, magnificence; on the other, physical suffering, disease, chagrin, sadness, mortification.  The design gives one suggestion: here is the lord overlooking his dominion and alternately contemplating a globe; it looks like the malady, the mortification, the sadness of Alexander amidst the grandeur of this world’s wealth.  It also signifies that a young lady may expect trivial disappointments.",
        "Reversed": "Surprise, wonder, enchantment, emotion, trouble, fear.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg",
        "Description":"A tall man looks from a battlemented roof over sea and shore; he holds a globe in his right hand, while a staff in his left rests on the battlement; another is fixed in a ring. The Rose and Cross and Lily should be noticed on the left side."
    },
    {
        "Id": 31,
        "Title": "III of Wands",
        "Suit": "Wands",
        "Ordinal": 3,
        "OrdinalName": "III",
        "GenderedCard": "Non-specific",
        "Normal": "The figure on the card symbolises established strength, enterprise, effort, trade, commerce, discovery; his ships, bearing his merchandise, sail over the sea.  A very good card; collaboration will favour enterprise.",
        "Reversed": "The end of troubles, suspension or end of adversity, toil and disappointment.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg",
        "Description":"A calm, stately personage, with his back turned, looking from a cliff’s edge at ships passing over the sea. Three staves are planted in the ground, and he leans slightly on one of them."
    },
    {
        "Id": 32,
        "Title": "IV of Wands",
        "Suit": "Wands",
        "Ordinal": 4,
        "OrdinalName": "IV",
		"Gendered":true,
        "GenderedCard": "Non-specific",
        "Normal": "They are for once almost on the surface - country life, repose, concord, harmony, prosperity, peace, and the perfected work of these; unexpected good fortune.",
        "Reversed": "The meaning remains unaltered; it is prosperity, increase, felicity, beauty, embellishment.  A married woman will have beautiful children.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg",
        "Description":"From the four great staves planted in the foreground there is a great garland suspended; two female figures uplift nosegays; at their side is a bridge over a moat, leading to an old manorial house."
    },
    {
        "Id": 33,
        "Title": "V of Wands",
        "Suit": "Wands",
        "Ordinal": 5,
        "OrdinalName": "V",
        "GenderedCard": "Non-specific",
        "Normal": "Imitation, as, for example, sham fight, the strenuous competition and struggle of the search after riches and fortune.  Hence some attributions say that it is a card of gold, gain, opulence, and indicates success in financial speculation.",
        "Reversed": "Litigation, disputes, trickery, contradiction.  Quarrels may be turned to advantage.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg",
        "Description":"A posse of youths, who are brandishing staves, as if in sport or strife. It is mimic warfare."
    },
    {
        "Id": 34,
        "Title": "VI of Wands",
        "Suit": "Wands",
        "Ordinal": 6,
        "OrdinalName": "VI",
        "GenderedCard": "Non-specific",
        "Normal": "The card has been so designed that it can convey several meanings: on the surface, it is a victor triumphing, but it is also great news, such as might be carried in state by the King’s courier; it is expectation crowned with its own desire, the crown of hope, and so on.  It also signifies that servants may lose the confidence of their masters, or that a young lady may be betrayed by a friend.",
        "Reversed": "Apprehension, fear, as of a victorious enemy at the gate, treachery, disloyalty, as of gates being opened to the enemy.  Also fulfilment of deferred hope",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg",
        "Description":"A laurelled horseman bears one staff adorned with a laurel crown; footmen with staves are at his side. "
    },
    {
        "Id": 35,
        "Title": "VII of Wands",
        "Suit": "Wands",
        "Ordinal": 7,
        "OrdinalName": "VII",
        "GenderedCard": "Non-specific",
        "Normal": "It is a card of valour, for, on the surface, six are attacking one, who has, however, the vantage position.  On the intellectual plane, it signifies discussion, worldly strife; in business - negotiations, war of trade, barter, competition.  It is also a card of success, for the combatant is on the top and their enemies may be unable to reach them.  In addition, it signifies a dark child.",
        "Reversed": "Perplexity, embarrassments, anxiety.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg",
        "Description":"A young man on a craggy eminence brandishing a staff; six other staves are raised towards him from below. "
    },
    {
        "Id": 36,
        "Title": "VIII of Wands",
        "Suit": "Wands",
        "Ordinal": 8,
        "OrdinalName": "VIII",
        "GenderedCard": "Non-specific",
        "Normal": "Activity in undertakings, the path of such activity, swiftness, as that of an express messenger; great haste, great hope, speed towards an end which promises happiness; generally, that which is on the move.  Also: the arrows of love; domestic disputes for a married person.",
        "Reversed": "Arrows of jealousy, internal dispute, stingings of conscience, quarrels.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg",
        "Description":"The card represents motion through the immovable-a flight of wands through an open country; but they draw to the term of their course. That which they signify is at hand; it may be even on the threshold."
    },
    {
        "Id": 37,
        "Title": "IX of Wands",
        "Suit": "Wands",
        "Ordinal": 9,
        "OrdinalName": "IX",
        "GenderedCard": "Non-specific",
        "Normal": "The card signifies strength in opposition.  If attacked, the subject of the card will meet the onslaught boldly.  With this main significance there are all its possible adjuncts - delay, suspension, adjournment.  Generally speaking, a bad card.",
        "Reversed": "Obstacles, adversity, calamity.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg",
        "Description":"The figure leans upon his staff and has an expectant look, as if awaiting an enemy. Behind are eight other staves&#8212;erect, in orderly disposition, like a palisade. "
    },
    {
        "Id": 38,
        "Title": "X of Wands",
        "Suit": "Wands",
        "Ordinal": 10,
        "OrdinalName": "X",
        "GenderedCard": "Non-specific",
        "Normal": "A card of many significances, and some of the readings cannot be harmonised.  I set aside that which connects it with honor and good faith.  It is oppression simply, but it is also fortune, gain, any kind of success of these things. It is also a card for false-seeming, disguise, perfidy.  The place which the figure is approaching may suffer from the rods that he carries.  Success is stultified if the nine of Swords follows, and if it is a question of a lawsuit, there will be certain loss.  Difficulties and contradictions are signified, if near a good good card.",
        "Reversed": "Contrarieties, difficulties, intrigues, and their analogies.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg",
        "Description":"A man oppressed by the weight of the ten staves which he is carrying."
    },
    {
        "Id": 39,
        "Title": "Page of Wands",
        "Suit": "Wands",
        "Ordinal": 11,
        "OrdinalName": "Page",
        "GenderedCard": "Male",
        "Normal": "Dark young man, faithful, a lover, an envoy, a postman. Young man of family in search of young lady.  Beside a man, he will bear favourable testimony concerning him.  A dangerous rival, if followed by the Page of cups.  He has the chief qualities of his suit.",
        "Reversed": "Anecdotes, announcements evil news.  Also indecision and say instability which accompanies it.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg",
        "Description":"In a scene similar to the former, a young man stands in the act of proclamation. He is unknown but faithful, and his tidings are strange."
    },
    {
        "Id": 40,
        "Title": "Knight of Wands",
        "Suit": "Wands",
        "Ordinal": 12,
        "OrdinalName": "Knight",
		"Gendered":true,
        "GenderedCard": "Male",
        "Normal": "Departure, absence, flight, emigration.  A dark young man, friendly.  Change of residence.  A bad card, according to some readings; alienation.",
        "Reversed": "Rupture, division, interruption, discord.  For a woman, marriage probably frustrated.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg",
        "Description":"He is shewn as if upon a journey, armed with a short wand, and although mailed is not on a warlike errand. He is passing mounds or pyramids. The motion of the horse is a key to the character of its rider, and suggests the precipitate mood, or things connected therewith."
    },
    {
        "Id": 41,
        "Title": "Queen of Wands",
        "Suit": "Wands",
        "Ordinal": 13,
        "OrdinalName": "Queen",
		"Gendered":true,
        "GenderedCard": "Female",
        "Normal": "A dark woman, countrywoman, friendly, chaste, loving, honourable.  If the card beside her signifies a man, she is well disposed towards him; if a woman, she is interested in the Querent.  Also: love of money; a good harvest - which may be taken in several senses.",
        "Reversed": "Good, economical, obliging, serviceable; goodwill towards the queen, without the opportunity to exercise it.  Signifies also opposition, jealousy, even deceit and infidelity.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg",
        "Description":"The Wands throughout this suit are always in leaf, as it is a suit of life and animation. Emotionally and otherwise, the Queen’s personality corresponds to that of the King, but is more magnetic."
    },
    {
        "Id": 42,
        "Title": "King of Wands",
        "Suit": "Wands",
        "Ordinal": 14,
        "OrdinalName": "King",
        "GenderedCard": "Male",
        "Normal": "Dark man, friendly, countryman, generally married, honest and conscientious.  Generally a favourable card; may signify a good marriage.",
        "Reversed": "Good, but severe; austere, yet tolerant.  Also advice that should be followed.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg",
        "Description":"The physical and emotional nature to which this card is attributed is dark, ardent, lithe, animated, impassioned, noble. The King uplifts a flowering wand, and wears, like his three correspondences in the remaining suits, what is called a cap of maintenance beneath his crown. He connects with the symbol of the lion, which is emblazoned on the back of his throne."
    },
    {
        "Id": 43,
        "Title": "Ace of Swords",
        "Suit": "Swords",
        "Ordinal": 1,
        "OrdinalName": "Ace",
		"Gendered":true,
        "GenderedCard": "Non-specific",
        "Normal": "Triumph, The excessive degree in everything conquest, triumph of force.  It is a card of great force, in love as well as in hatred; it can indicate great prosperity or great misery.",
        "Reversed": "The same, but the results are disastrous; another account says conception, childbirth, augmentation, multiplicity.  For a woman, marriage broken off through her own imprudence.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg",
        "Description":"A hand issues from a cloud, grasping as word, the point of which is encircled by a crown."
    },
    {
        "Id": 44,
        "Title": "II of Swords",
        "Suit": "Swords",
        "Ordinal": 2,
        "OrdinalName": "II",
        "GenderedCard": "Female",
        "Normal": "Conformity and the equipoise which it suggests, courage, friendship, concord in a state of arms, affection, intimacy.  Also: gifts for a lady; influential protection for a man in search of help.",
        "Reversed": "Imposture, falsehood, duplicity, disloyalty.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg",
        "Description":"A hoodwinked female figure balances two swords upon her shoulders. "
    },
    {
        "Id": 45,
        "Title": "III of Swords",
        "Suit": "Swords",
        "Ordinal": 3,
        "OrdinalName": "III",
        "GenderedCard": "Non-specific",
        "Normal": "Removal, absence, delay, division, rupture, dispersion, and all that the design signifies naturally.",
        "Reversed": "Mental alienation, error, loss, distraction, disorder, confusion.  A meeting with one of whom the Querent has compromised; also a nun.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg",
        "Description":"Three swords piercing a heart; cloud and rain behind. "
    },
    {
        "Id": 46,
        "Title": "IV of Swords",
        "Suit": "Swords",
        "Ordinal": 4,
        "OrdinalName": "IV",
        "GenderedCard": "Non-specific",
        "Normal": "A bad card; vigilance, retreat, solitude, hermits repose, exile,  tomb and coffin.",
        "Reversed": "Circumspection, economy, avarice, precaution, testament; a certain success may be expected by wise administration of affairs.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg",
        "Description":"The effigy of a knight in the attitude of prayer, at full length upon his tomb. "
    },
    {
        "Id": 47,
        "Title": "V of Swords",
        "Suit": "Swords",
        "Ordinal": 5,
        "OrdinalName": "V",
        "GenderedCard": "Non-specific",
        "Normal": "Degradation, destruction, reversal, infamy, dishonour, loss; an attack on the fortune of the Querent.",
        "Reversed": "The same; burial and obsequies.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg",
        "Description":"A disdainful man looks after two retreating and dejected figures. Their swords lie upon the ground. He carries two others on his left shoulder, and a third sword is in his right hand, point to earth. He is the master in possession of the field. "
    },
    {
        "Id": 48,
        "Title": "VI of Swords",
        "Suit": "Swords",
        "Ordinal": 6,
        "OrdinalName": "VI",
        "GenderedCard": "Non-specific",
        "Normal": "Journey by water, route, way, envoy, commissionary, expedient.",
        "Reversed": "Declaration, confession, publicity; unfavourable issue of a lawsuit; one account says that it is a proposal of love.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg",
        "Description":"A ferryman carrying passengers in his punt to the further shore. The course is smooth, and seeing that the freight is light, it may be noted that the work is not beyond his strength."
    },
    {
        "Id": 49,
        "Title": "VII of Swords",
        "Suit": "Swords",
        "Ordinal": 7,
        "OrdinalName": "VII",
        "GenderedCard": "Female",
        "Normal": "A dark girl; design, attempts, wish, hope, confidence; also quarrelling, a plan that may fail, annoyance.  A good card; it promises a country life after a competence has been secured.",
        "Reversed": "Good advice (probably neglected), counsel, instruction, slander, babbling.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg",
        "Description":"A man in the act of carrying away five swords rapidly; the two others of the card remain stuck in the ground. A camp is close at hand. "
    },
    {
        "Id": 50,
        "Title": "VIII of Swords",
        "Suit": "Swords",
        "Ordinal": 8,
        "OrdinalName": "VIII",
		"Gendered":true,
        "GenderedCard": "Non-specific",
        "Normal": "Bad news, violent chagrin, crisis, censure, power in trammels, conflict, calumny; also sickness.  For a woman, scandal spread in her respect.",
        "Reversed": "Disquiet, difficulty, opposition, accident, treachery, fatality; what is unforeseen; departure of a relative.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg",
        "Description":"A woman, bound and hoodwinked, with the swords of the card about her. Yet it is rather a card of temporary durance than of irretrievable bondage."
    },
    {
        "Id": 51,
        "Title": "IX of Swords",
        "Suit": "Swords",
        "Ordinal": 9,
        "OrdinalName": "IX",
        "GenderedCard": "Non-specific",
        "Normal": "An ecclesiastic, a priest; generally, generally a card of bad  omen, predicting death, failure, miscarriage, delay, deception, disappointment, despair.",
        "Reversed": "Imprisonment, suspicion, doubt, reasonable fear, shame.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg",
        "Description":"One seated on her couch in lamentation, with the swords over her. She is as one who knows no sorrow which is like unto hers. It is a card of utter desolation. "
    },
    {
        "Id": 52,
        "Title": "X of Swords",
        "Suit": "Swords",
        "Ordinal": 10,
        "OrdinalName": "X",
        "GenderedCard": "Non-specific",
        "Normal": "Whatever is intimated by the prostrate figure on the cards; also pain, affliction, tears, sadness, desolation.  If followed by Ace and King, the card signifies imprisonment; for a girl or wife, treason on the part of friends.",
        "Reversed": "Advantage, profit, success, favour, but none of these are permanent; also power and authority.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg",
        "Description":"A prostrate figure, pierced by all the swords belonging to the card. "
    },
    {
        "Id": 53,
        "Title": "Page of Swords",
        "Suit": "Swords",
        "Ordinal": 11,
        "OrdinalName": "Page",
        "GenderedCard": "Male",
        "Normal": "Authority, overseeing, secret service, vigilance, spying, examination, and the qualities belonging to these activities; an indiscreet person will pry into the querent’s secrets.",
        "Reversed": "More evil side of these qualities; what is unforeseen, unprepared state; sickness is also intimated.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg",
        "Description":"A lithe, active figure holds a sword upright in both hands, while in the act of swift walking. He is passing over rugged land, and about his way the clouds are collocated wildly. He is alert and lithe, looking this way and that, as if an expected enemy might appear at any moment. "
    },
    {
        "Id": 54,
        "Title": "Knight of Swords",
        "Suit": "Swords",
        "Ordinal": 12,
        "OrdinalName": "Knight",
		"Gendered":true,
        "GenderedCard": "Male",
        "Normal": "A soldier, man of arms, satellite, stipendiary; heroic action predicted for soldier.  Skill, bravery, capacity, defence, address, enmity, wrath, war, destruction, opposition, resistance, ruin.",
        "Reversed": "Imprudence, incapacity, extravagance.  Dispute with an imbecile person; for a woman, struggle with a rival, who will be conquered.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg",
        "Description":"He is riding in full course, as if scattering his enemies. In the design he is really a prototypical hero of romantic chivalry. He might almost be Galahad, whose sword is swift and sure because he is clean of heart."
    },
    {
        "Id": 55,
        "Title": "Queen of Swords",
        "Suit": "Swords",
        "Ordinal": 13,
        "OrdinalName": "Queen",
        "GenderedCard": "Female",
        "Normal": "Widowhood, female sadness and embarrassment, absence, sterility,  mourning, privation, separation.",
        "Reversed": "a bad woman; malice, bigotry, artifice, prudery, deceit.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg",
        "Description":"Her right hand raises the weapon vertically and the hilt rests on an arm of her royal chair the left hand is extended, the arm raised her countenance is severe but chastened; it suggests familiarity with sorrow. It does not represent mercy, and, her sword notwithstanding, she is scarcely a symbol of power. "
    },
    {
        "Id": 56,
        "Title": "King of Swords",
        "Suit": "Swords",
        "Ordinal": 14,
        "OrdinalName": "King",
        "GenderedCard": "Male",
        "Normal": "Whatever arises out of the idea of judgment and all its connections - power, command, authority, militant intelligence, law, offices of the crown, and so on.  Hence also a lawyer, senator, doctor.",
        "Reversed": "A bad man; cruelty, perversity, barbarity, perfidy, evil intention.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg",
        "Description":"He sits in judgment, holding the unsheathed sign of his suit. He recalls, of course, the conventional Symbol of justice in the Trumps Major, and he may represent this virtue, but he is rather the power of life and death, in virtue of his office. "
    },
    {
        "Id": 57,
        "Title": "0 of Trumps: \u2018The Fool\u2019",
        "Suit": "Trumps",
        "Ordinal": -1,
        "OrdinalName": "0 (The Fool)",
        "GenderedCard": "Male",
        "Normal": "Innocence, freedom, originality, adventure, travel, foolishness, carelessness, idealism, youth, spontaneity, lack of commitment, new beginnings.",
        "Reversed": "Recklessness, carelessness, negligence, stupidity, distraction, apathy, irrationality, lack of fun, hope or faith.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/RWS_Tarot_00_Fool.jpg/343px-RWS_Tarot_00_Fool.jpg",
        "Description":"With light step, as if Earth and its trammels had little power to restrain him, a young man in gorgeous vestments pauses at the brink of a precipice among the great heights of the world; he surveys the blue distance before him-its expanse of sky rather than the prospect below. His act of eager walking is still indicated, though he is stationary at the given moment; his dog is still bounding. The edge which opens on the depth has no terror; it is as if angels were waiting to uphold him, if it came about that he leaped from the height. His countenance is full of intelligence and expectant dream. He has a rose in one hand and in the other a costly wand, from which depends over his right shoulder a wallet curiously embroidered. He is a prince of the other world on his travels through this one-all amidst the morning glory, in the keen air. The sun, which shines behind him, knows whence he came, whither he is going, and how he will return by another path after many days. He is the spirit in search of experience. Many symbols of the Instituted Mysteries are summarized in this card, which reverses, under high warrants, all the confusions that have preceded it.<br/>In his Manual of Cartomancy, Grand Orient has a curious suggestion of the office of Mystic Fool, as apart of his process in higher divination; but it might call for more than ordinary gifts to put it into operation. We shall see how the card fares according to the common arts of fortune-telling, and it will be an example, to those who can discern, of the fact, otherwise so evident, that the Trumps Major had no place originally in the arts of psychic gambling, when cards are used as the counters and pretexts. Of the circumstances under which this art arose we know, however, very little. The conventional explanations say that the Fool signifies the flesh, the sensitive life, and by a peculiar satire its subsidiary name was at one time the alchemist, as depicting folly at the most insensate stage."
    },
    {
        "Id": 58,
        "Title": "I of Trumps: \u2018The Magician\u2019",
        "Suit": "Trumps",
        "Ordinal": 1,
        "OrdinalName": "I (The Magician)",
		"Gendered":true,
        "GenderedCard": "Male",
        "Normal": "Skill, diplomacy, address; sickness, pain loss; disaster, self-confidence, will; the Querent, if male.",
        "Reversed": "Physician, Magus, mental disease, disgrace, disquiet",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
		"Description":"A youthful figure in the robe of a magician, having the countenance of divine Apollo, with smile of confidence and shining eyes. Above his head is the mysterious sign of the Holy Spirit, the sign of life, like an endless cord, the sign of infinity is the figure 8 in a horizontal position. About his waist is a serpent-cincture, the serpent appearing to devour its own tail. This is familiar to most as a conventional symbol of eternity, but here it indicates more especially the eternity of attainment in the spirit. In the Magician\u2019s right hand is a wand raised towards heaven, while the left hand is pointing to the earth. This dual sign is known in very high grades of the Instituted Mysteries; it shews the descent of grace, virtue and light, drawn from things above and derived to things below. The suggestion throughout is therefore the possession and communication of the Powers and Gifts of the Spirit. On the table in front of the Magician are the symbols of the four Tarot suits, signifying the elements of natural life, which lie like counters before the adept, and he adapts them as he wills. Beneath are roses and lilies, the <i>flos campi</i> and <i>lilium convallium</i>, changed into garden flowers, to shew the culture of aspiration. This card signifies the divine motive in man, reflecting God, the will in the liberation of its union with that which is above. It is also the unity of individual being on all planes, and in a very high sense it is thought, in the fixation thereof. With further reference to what I have called the sign of life and its connexion with the number 8, it may be remembered that Christian Gnosticism speaks of rebirth in Christ as a change \u2018unto the Ogdoad.\u2019 The mystic number is termed Jerusalem above, the Land flowing with Milk and Honey, the Holy Spirit and the Land of the Lord. According to Martinism, 8 is the number of Christ."
    },
    {
        "Id": 59,
        "Title": "II of Trumps: \u2018The High Priestess\u2019",
        "Suit": "Trumps",
        "Ordinal": 2,
        "OrdinalName": "II (The High Priestess)",
		"Gendered":true,
        "GenderedCard": "Female",
        "Normal": "Secrets, mystery, the future as yet unrevealed; If male: the woman who interests the Querent. If female: Silence, tenacity; wisdom, science",
        "Reversed": "Passion, moral or physical ardour, conceit, surface knowledge",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
        "Description":"She has the lunar crescent at her feet, a horned diadem on her head, with a globe in the middle place, and a large solar cross on her breast. The scroll in her hands is inscribed with the word <i>Tora</i>, signifying the Greater Law, the Secret Law and the second sense of the Word. It is partly covered by her mantle, to shew that some things are implied and some spoken. She is seated between the white and black pillars&#8212;J. and B.&#8212;of the mystic Temple, and the veil of the Temple is behind her: it is embroidered with palms and pomegranates. The vestments are flowing and gauzy, and the mantle suggests light&#8212;a shimmering radiance. She has been called occult Science on the threshold of the Sanctuary of Isis, but she is really the Secret Church, the House which is of God and man. She represents also the Second Marriage of the Prince who is no longer of this world; she is the spiritual Bride and Mother, the daughter of the stars and the Higher Garden of Eden. She is, in fine, the Queen of the borrowed light, but this is the light of all. She is the Moon nourished by the milk of the Supernal Mother.<br/>In a manner, she is also the Supernal Mother herself&#8212;that is to say, she is the bright reflection. It is in this sense of reflection that her truest and highest name in bolism is Shekinah&#8212;the co-habiting glory. According to Kabalism, there is a Shekinah both above and below. In the superior world it is called Binah, the Supernal Understanding which reflects to the emanations that are beneath. In the lower world it is MaIkuth&#8212;that world being, for this purpose, understood as a blessed Kingdom that with which it is made blessed being the Indwelling Glory. Mystically speaking, the Shekinah is the Spiritual Bride of the just man, and when he reads the Law she gives the Divine meaning. There are some respects in which this card is the highest and holiest of the Greater Arcana."
    },
    {
        "Id": 60,
        "Title": "III of Trumps: \u2018The Empress\u2019",
        "Suit": "Trumps",
        "Ordinal": 3,
        "OrdinalName": "III (The Empress)",
		"Gendered":true,
        "GenderedCard": "Female",
        "Normal": "Secrets, mystery, the future as yet unrevealed; the woman who interests the querent, if male. The querent if female; silence, tenacity, wisdom, science",
        "Reversed": "Passion, moral or physical ardour, conceit, surface knowledge",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
        "Description":"A stately figure, seated, having rich vestments and royal aspect, as of a daughter of heaven and earth. Her diadem is of twelve stars, gathered in a cluster. The symbol of Venus is on the shield which rests near her. A field of corn is ripening in front of her, and beyond there is a fall of water. The sceptre which she bears is surmounted by the globe of this world. She is the inferior Garden of Eden, the Earthly Paradise, all that is symbolized by the visible house of man. She is not Regina coeli, but she is still refugium peccatorum, the fruitful mother of thousands. There are also certain aspects in which she has been correctly described as desire and the wings thereof, as the woman clothed with the sun, as <i>Gloria Mundi</i> and the veil of the <i>Sanctum Sanctorum</i>; but she is not, I may add, the soul that has attained wings, unless all the symbolism is counted up another and unusual way. She is above all things universal fecundity and the outer sense of the Word. This is obvious, because there is no direct message which has been given to man like that which is borne by woman; but she does not herself carry its interpretation.<br/>In another order of ideas, the card of the Empress signifies the door or gate by which an entrance is obtained into this life, as into the Garden of Venus; and then the way which leads out therefrom, into that which is beyond, is the secret known to the High Priestess: it is communicated by her to the elect. Most old attributions of this card are completely wrong on the symbolism&#8212;as, for example, its identification with the Word, Divine Nature, the Triad, and so forth."
    },
    {
        "Id": 61,
        "Title": "IV of Trumps: \u2018The Emperor\u2019",
        "Suit": "Trumps",
        "Ordinal": 4,
        "OrdinalName": "IV (The Emperor)",
        "GenderedCard": "Male",
        "Normal": "Stability, power, protection: a great; person aid, reason, conviction",
        "Reversed": "Benevolence, compassion, credit; also confusion to enemies, obstruction, immaturity",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
        "Description":"He has a form of the <i>Crux ansata</i> for his sceptre and a globe in his left hand. He is a crowned monarch&#8212;commanding, stately, seated on a throne, the arms of which axe fronted by rams’ heads. He is executive and realization, the power of this world, here clothed with the highest of its natural attributes. He is occasionally represented as seated on a cubic stone, which, however, confuses some of the issues. He is the virile power, to which the Empress responds, and in this sense is he who seeks to remove the Veil of Isis; yet she remains virgo intacta.<br/>It should be understood that this card and that of the Empress do not precisely represent the condition of married life, though this state is implied. On the surface, as I have indicated, they stand for mundane royalty, uplifted on the seats of the mighty; but above this there is the suggestion of another presence. They signify also&#8212;and the male figure especially&#8212;the higher kingship, occupying the intellectual throne. Hereof is the lordship of thought rather than of the animal world. Both personalities, after their own manner, are \u2018full of strange experience\u2019, but theirs is not consciously the wisdom which draws from a higher world. The Emperor has been described as (a) will in its embodied form, but this is only one of its applications, and (b) as an expression of virtualities contained in the Absolute Being&#8212;but this is fantasy."
    },
    {
        "Id": 62,
        "Title": "V of Trumps: \u2018The Hierophant\u2019",
        "Suit": "Trumps",
        "Ordinal": 5,
        "OrdinalName": "V (The Hierophant)",
        "GenderedCard": "Male",
        "Normal": "Marriage alliance, captivity, servitude; by another account mercy and goodness; inspiration; the man to whom the querent has recourse.",
        "Reversed": "Society, good understanding, concord, over-kindness, weakness.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
        "Description":"He wears the triple crown and is seated between two pillars, but they are not those of the Temple which is guarded by the High Priestess. In his left hand he holds a sceptre terminating in the triple cross, and with his right hand he gives the well-known ecclesiastical sign which is called that of esotericism, distinguishing between the manifest and concealed part of doctrine. It is noticeable in this connexion that the High Priestess makes no sign. At his feet are the crossed keys, and two priestly ministers in albs kneel before him. He has been usually called the Pope, which is a particular application of the more general office that he symbolizes. He is the ruling power of external religion, as the High Priestess is the prevailing genius of the esoteric, withdrawn power. The proper meanings of this card have suffered woeful admixture from nearly all hands. Grand Orient says truly that the Hierophant is the power of the keys, exoteric orthodox doctrine, and the outer side of the life which leads to the doctrine; but he is certainly not the prince of occult doctrine, as another commentator has suggested.<br/>He is rather the summa totius theologiæ, when it has passed into the utmost rigidity of expression; but he symbolizes also all things that are righteous and sacred on the manifest side. As such, he is the channel of grace belonging to the world of institution as distinct from that of Nature, and he is the leader of salvation for the human race at large. He is the order and the head of the recognized hierarchy, which is the reflection of another and greater hierarchic order; but it may so happen that the pontiff forgets the significance of this his symbolic state and acts as if he contained within his proper measures all that his sign signifies or his symbol seeks to shew forth. He is not, as it has been thought, philosophy-except on the theological side; he is not inspiration; and he is not religion, although he is a mode of its expression."
    },
    {
        "Id": 63,
        "Title": "VI of Trumps: \u2018The Lovers\u2019",
        "Suit": "Trumps",
        "Ordinal": 6,
        "OrdinalName": "VI (The Lovers)",
        "GenderedCard": "Non-specific",
        "Normal": "Attraction, love, beauty, trials overcome",
        "Reversed": "Failure,  foolish designs",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg",
        "Description":"The sun shines in the zenith, and beneath is a great winged figure with arms extended, pouring down influences. In the foreground are two human figures, male and female, unveiled before each other, as if Adam and Eve when they first occupied the paradise of the earthly body. Behind the man is the Tree of Life, bearing twelve fruits, and the Tree of the Knowledge of Good and Evil is behind the woman; the serpent is twining round it. The figures suggest youth, virginity, innocence and love before it is contaminated by gross material desire. This is in all simplicity the card of human love, here exhibited as part of the way, the truth and the life. It replaces, by recourse to first principles, the old card of marriage, which I have described previously, and the later follies which depicted man between vice and virtue. In a very high sense, the card is a mystery of the Covenant and Sabbath.<br/>The suggestion in respect of the woman is that she signifies that attraction towards the sensitive life which carries within it the idea of the Fall of Man, but she is rather the working of a Secret Law of Providence than a willing and conscious temptress. It is through her imputed lapse that man shall arise ultimately, and only by her can he complete himself. The card is therefore in its way another intimation concerning the great mystery of womanhood. The old meanings fall to pieces of necessity with the old pictures, but even as interpretations of the latter, some of them were of the order of commonplace and others were false in symbolism."
    },
    {
        "Id": 64,
        "Title": "VII of Trumps: \u2018The Chariot\u2019",
        "Suit": "Trumps",
        "Ordinal": 7,
        "OrdinalName": "VII (The Chariot)",
        "GenderedCard": "Non-specific",
        "Normal": "succour, providence; also war triumph, presumption, vengeance, trouble",
        "Reversed": "Riot, quarrel, dispute, litigation, defeat",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
        "Description":"An erect and princely figure carrying a drawn sword and corresponding, broadly speaking, to the traditional description which I have given in the first part. On the shoulders of the victorious hero are supposed to be the Urim and Thummim. He has led captivity captive; he is conquest on all planes&#8212;in the mind, in science, in progress, in certain trials of initiation. He has thus replied to the sphinx, and it is on this account that I have accepted the variation of Éliphas Lévi; two sphinxes thus draw his chariot. He is above all things triumph in the mind.<br/>It is to be understood for this reason (a) that the question of the sphinx is concerned with a Mystery of Nature and not of the world of Grace, to which the charioteer could offer no answer; (b) that the planes of his conquest are manifest or external and not within himself; (c) that the liberation which he effects may leave himself in the bondage of the logical understanding; (d) that the tests of initiation through which he has passed in triumph are to be understood physically or rationally; and (e) that if he came to the pillars of that Temple between which the High Priestess is seated, he could not open the scroll called Tora, nor if she questioned him could he answer. He is not hereditary royalty and he is not priesthood."
    },
    {
        "Id": 65,
        "Title": "VIII of Trumps: \u2018Strength\u2019",
        "Suit": "Trumps",
        "Ordinal": 8,
        "OrdinalName": "VIII (Strength)",
        "GenderedCard": "Female",
        "Normal": "Power, energy, action, courage, magnanimity.",
        "Reversed": "Despotism, abuse of power, weakness, discord.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg",
        "Description":"A woman, over whose head there broods the same symbol of life which we have seen in the card of the Magician, is closing the jaws of a lion. The only point in which this design differs from the conventional presentations is that her beneficent fortitude has already subdued the lion, which is being led by a chain of flowers. For reasons which satisfy myself, this card has been interchanged with that of justice, which is usually numbered eight. As the variation carries nothing with it which will signify to the reader, there is no cause for explanation. Fortitude, in one of its most exalted aspects, is connected with the Divine Mystery of Union; the virtue, of course, operates in all planes, and hence draws on all in its symbolism. It connects also with innocentia inviolata, and with the strength which resides in contemplation.<br/>These higher meanings are, however, matters of inference, and I do not suggest that they are transparent on the surface of the card. They are intimated in a concealed manner by the chain of flowers, which signifies, among many other things, the sweet yoke and the light burden of Divine Law, when it has been taken into the heart of hearts. The card has nothing to do with self-confidence in the ordinary sense, though this has been suggested&#8212;but it concerns the confidence of those whose strength is God, who have found their refuge in Him. There is one aspect in which the lion signifies the passions, and she who is called Strength is the higher nature in its liberation. It has walked upon the asp and the basilisk and has trodden down the lion and the dragon."
    },
    {
        "Id": 66,
        "Title": "IX of Trumps: \u2018The Hermit\u2019",
        "Suit": "Trumps",
        "Ordinal": 9,
        "OrdinalName": "IX (The Hermit)",
        "GenderedCard": "Male",
        "Normal": "Prudence: also and especially treason, dissimulation, roguery, corruption.",
        "Reversed": "Concealment, disguise, policy, fear, unreasoned caution.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg",
        "Description":"The variation from the conventional models in this card is only that the lamp is not enveloped partially in the mantle of its bearer, who blends the idea of the Ancient of Days with the Light of the World It is a star which shines in the lantern. I have said that this is a card of attainment, and to extend this conception the figure is seen holding up his beacon on an eminence. Therefore the Hermit is not, as Court de Gebelin explained, a wise man in search of truth and justice; nor is he, as a later explanation proposes, an especial example of experience. His beacon intimates that \u2018where I am, you also may be.\u2019<br/>It is further a card which is understood quite incorrectly when it is connected with the idea of occult isolation, as the protection of personal magnetism against admixture. This is one of the frivolous renderings which we owe to Éliphas Lévi. It has been adopted by the French Order of Martinism and some of us have heard a great deal of the Silent and Unknown Philosophy enveloped by his mantle from the knowledge of the profane. In true Martinism, the significance of the term Philosophe inconnu was of another order. It did not refer to the intended concealment of the Instituted Mysteries, much less of their substitutes, but&#8212;like the card itself&#8212;to the truth that the Divine Mysteries secure their own protection from those who are unprepared."
    },
    {
        "Id": 67,
        "Title": "X of Trumps: \u2018Wheel of Fortune\u2019",
        "Suit": "Trumps",
        "Ordinal": 10,
        "OrdinalName": "X (Wheel of Fortune)",
        "GenderedCard": "Non-specific",
        "Normal": "Destiny, fortune, success, luck, happiness.",
        "Reversed": "Increase, abundance, superfluity.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
        "Description":"In this symbol I have again followed the reconstruction of Éliphas Lévi, who has furnished several variants. It is legitimate&#8212;as I have intimated&#8212;to use Egyptian symbolism when this serves our purpose, provided that no theory of origin is implied therein. I have, however, presented Typhon in his serpent form. The symbolism is, of course, not exclusively Egyptian, as the four Living Creatures of Ezekiel occupy the angles of the card, and the wheel itself follows other indications of Lévi in respect of Ezekiel’s vision, as illustrative of the particular Tarot Key. With the French occultist, and in the design itself, the symbolic picture stands for the perpetual motion of a fluidic universe and for the flux of human life. The Sphinx is the equilibrium therein. The transliteration of Taro as Rota is inscribed on the wheel, counterchanged with the letters of the Divine Name&#8212;to shew that Providence is imphed through all. But this is the Divine intention within, and the similar intention without is exemplified by the four Living Creatures. Sometimes the sphinx is represented couchant on a pedestal above, which defrauds the symbolism by stultifying the essential idea of stability amidst movement.<br/>Behind the general notion expressed in the symbol there lies the denial of chance and the fatality which is implied therein. It may be added that, from the days of Lévi onward, the occult explanations of this card are&#8212;even for occultism itself&#8212;of a singularly fatuous kind. It has been said to mean principle, fecundity, virile honour, ruling authority, etc. The findings of common fortune-telling are better than this on their own plane."
    },
    {
        "Id": 68,
        "Title": "XI of Trumps: \u2018Justice\u2019",
        "Suit": "Trumps",
        "Ordinal": 11,
        "OrdinalName": "XI (Justice)",
        "GenderedCard": "Female",
        "Normal": "Equity, rightness, probity, executive.",
        "Reversed": "Law in all departments, bigotry, bias, excessive severity.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
        "Description":"As this card follows the traditional symbolism and carries above all its obvious meanings, there is little to say regarding it outside the few considerations collected in the first part, to which the reader is referred.<br/>It will be seen, however, that the figure is seated between pillars, like the High Priestess, and on this account it seems desirable to indicate that the moral principle which deals unto every man according to his works&#8212;while, of course, it is in strict analogy with higher things;&#8212;differs in its essence from the spiritual justice which is involved in the idea of election. The latter belongs to a mysterious order of Providence, in virtue of which it is possible for certain men to conceive the idea of dedication to the highest things. The operation of this is like the breathing of the Spirit where it wills, and we have no canon of criticism or ground of explanation concerning it. It is analogous to the possession of the fairy gifts and the high gifts and the gracious gifts of the poet: we have them or have not, and their presence is as much a mystery as their absence. The law of Justice is not however involved by either alternative. In conclusion, the pillars of Justice open into one world and the pillars of the High Priestess into another."
    },
    {
        "Id": 69,
        "Title": "XII of Trumps: \u2018The Hanged Man\u2019",
        "Suit": "Trumps",
        "Ordinal": 12,
        "OrdinalName": "XII (The Hanged Man)",
        "GenderedCard": "Male",
        "Normal": "Wisdom, circumspection, discernment, trials, sacrifice, intuition, divination, prophecy.",
        "Reversed": "Selfishness, the crowd, body politic.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
        "Description":"The gallows from which he is suspended forms a Tau cross, while the figure&#8212;from the position of the legs&#8212;forms a fylfot cross. There is a nimbus about the head of the seeming martyr. It should be noted (1) that the tree of sacrifice is living wood, with leaves thereon; (2) that the face expresses deep entrancement, not suffering; (3) that the figure, as a whole, suggests life in suspension, but life and not death. It is a card of profound significance, but all the significance is veiled. One of his editors suggests that Éliphas Lévi did not know the meaning, which is unquestionable nor did the editor himself. It has been called falsely a card of martyrdom, a card a of prudence, a card of the Great Work, a card of duty; but we may exhaust all published interpretations and find only vanity. I will say very simply on my own part that it expresses the relation, in one of its aspects, between the Divine and the Universe.<br/>He who can understand that the story of his higher nature is imbedded in this symbolism will receive intimations concerning a great awakening that is possible, and will know that after the sacred Mystery of Death there is a glorious Mystery of Resurrection."
    },
    {
        "Id": 70,
        "Title": "XIII of Trumps: \u2018Death\u2019",
        "Suit": "Trumps",
        "Ordinal": 13,
        "OrdinalName": "XIII (Death)",
        "GenderedCard": "Male",
        "Normal": "End, mortality, destruction, corruption.",
        "Reversed": "inertia, sleep, lethargy, petrification , somnambulism.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg",
        "Description":"The veil or mask of life is perpetuated in change, transformation and passage from lower to higher, and this is more fitly represented in the rectified Tarot by one of the apocalyptic visions than by the crude notion of the reaping skeleton. Behind it lies the whole world of ascent in the spirit. The mysterious horseman moves slowly, bearing a black banner emblazoned with the Mystic Rose, which signifies life. Between two pillars on the verge of the horizon there shines the sun of immortality. The horseman carries no visible weapon, but king and child and maiden fall before him, while a prelate with clasped hands awaits his end.<br/>There should be no need to point out that the suggestion of death which I have made in connection with the previous card is, of course, to be understood mystically, but this is not the case in the present instance. The natural transit of man to the next stage of his being either is or may be one form of his progress, but the exotic and almost unknown entrance, while still in this life, into the state of mystical death is a change in the form of consciousness and the passage into a state to which ordinary death is neither the path nor gate. The existing occult explanations of the 13th card are, on the whole, better than usual, rebirth, creation, destination, renewal, and the rest."
    },
    {
        "Id": 71,
        "Title": "XIV of Trumps: \u2018Temperance\u2019",
        "Suit": "Trumps",
        "Ordinal": 14,
        "OrdinalName": "XIV (Temperance)",
        "GenderedCard": "Female",
        "Normal": "Economy, moderation, frugality, management, accommodation.",
        "Reversed": "Things connected with churches.  Religions, sects, the priesthood.  Also disunion, unfortunate combinations, competing interests.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg",
        "Description":"A winged angel, with the sign of the sun upon his forehead and on his breast the square and triangle of the septenary. I speak of him in the masculine sense, but the figure is neither male nor female. It is held to be pouring the essences of life from chalice to chalice. It has one foot upon the earth and one upon waters, thus illustrating the nature of the essences. A direct path goes up to certain heights on the verge of the horizon, and above there is a great light, through which a crown is seen vaguely. Hereof is some part of the Secret of Eternal Life, as it is possible to man in his incarnation. All the conventional emblems are renounced herein.<br/>So also are the conventional meanings, which refer to changes in the seasons, perpetual movement of life and even the combination of ideas. It is, moreover, untrue to say that the figure symbolizes the genius of the sun, though it is the analogy of solar light, realized in the third part of our human triplicity. It is called Temperance fantastically, because, when the rule of it obtains in our consciousness, it tempers, combines and harmonises the psychic and material natures. Under that rule we know in our rational part something of whence we came and whither we are going."
    },
    {
        "Id": 72,
        "Title": "XV of Trumps: \u2018The Devil\u2019",
        "Suit": "Trumps",
        "Ordinal": 15,
        "OrdinalName": "XV (The Devil)",
        "GenderedCard": "Male",
        "Normal": "ravage , violence, vehemence, extraordinary efforts, force, fatality; that which is predestined but not for this reason evil.",
        "Reversed": "Evil, fatality, weakness, pettiness, blindness.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg",
        "Description":"The design is an accommodation, mean or harmony, between several motives mentioned in the first part. The Horned Goat of Mendes, with wings like those of a bat, is standing on an altar. At the pit of the stomach there is the sign of Mercury. The right hand is upraised and extended, being the reverse of that benediction which is given by the Hierophant in the fifth card. In the left hand there is a great flaming torch, inverted towards the earth. A reversed pentagram is on the forehead. There is a ring in front of the altar, from which two chains are carried to the necks of two figures, male and female. These are analogous with those of the fifth card, as if Adam and Eve after the Fall. Hereof is the chain and fatality of the material life.<br/>The figures are tailed, to signify the animal nature, but there is human intelligence in the faces, and he who is exalted above them is not to be their master for ever. Even now, he is also a bondsman, sustained by the evil that is in him and blind to the liberty of service. With more than his usual derision for the arts which he pretended to respect and interpret as a master therein, Éliphas Lévi affirms that the Baphometic figure is occult science and magic. Another commentator says that in the Divine world it signifies predestination, but there is no correspondence in that world with the things which below are of the brute. What it does signify is the Dweller on the Threshold without the Mystical Garden when those are driven forth therefrom who have eaten the forbidden fruit."
    },
    {
        "Id": 73,
        "Title": "XVI of Trumps: \u2018The Tower\u2019",
        "Suit": "Trumps",
        "Ordinal": 16,
        "OrdinalName": "XVI (The Tower)",
        "GenderedCard": "Non-specific",
        "Normal": "Misery, distress, indigentce, adversity, Calamity, disgrace, deception, ruin.",
        "Reversed": "According to one account, the same in lesser degree; also oppression, imprisonment, tyranny.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg",
        "Description":"Occult explanations attached to this card are meagre and mostly disconcerting. It is idle to indicate that it depicts min in all its aspects, because it bears this evidence on the surface. It is said further that it contains the first allusion to a material building, but I do not conceive that the Tower is more or less material than the pillars which we have met with in three previous cases. I see nothing to warrant Papus in supposing that it is literally the fall of Adam, but there is more in favour of his alternative&#8212;that it signifies the materialization of the spiritual word. The bibliographer Christian imagines that it is the downfall of the mind, seeking to penetrate the mystery of God. I agree rather with Grand Orient that it is the ruin of the House of We, when evil has prevailed therein, and above all that it is the rending of a House of Doctrine. I understand that the reference is, however, to a House of Falsehood. It illustrates also in the most comprehensive way the old truth that \u2018except the Lord build the house, they labour in vain that build it.\u2019<br/>There is a sense in which the catastrophe is a reflection from the previous card, but not on the side of the symbolism which I have tried to indicate therein. It is more correctly a question of analogy; one is concerned with the fall into the material and animal state, while the other signifies destruction on the intellectual side. The Tower has been spoken of as the chastisement of pride and the intellect overwhelmed in the attempt to penetrate the Mystery of God; but in neither case do these explanations account for the two persons who are the living sufferers. The one is the literal word made void and the other its false interpretation. In yet a deeper sense, it may signify also the end of a dispensation, but there is no possibility here for the consideration of this involved question."
    },
    {
        "Id": 74,
        "Title": "XVII of Trumps: \u2018The Star\u2019",
        "Suit": "Trumps",
        "Ordinal": 17,
        "OrdinalName": "XVII (The Star)",
        "GenderedCard": "Female",
        "Normal": "Loss, theft, privation, abandonment; another reading says hope and bright prospects.",
        "Reversed": "Arrogance, haughtiness, impotence",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg",
        "Description":"A great, radiant star of eight rays, surrounded by seven lesser stars&#8212;also of eight rays. The female figure in the foreground is entirely naked. Her left knee is on the land and her right foot upon the water. She pours Water of Life from two great ewers, irrigating sea and land. Behind her is rising ground and on the right a shrub or tree, whereon a bird alights. The figure expresses eternal youth and beauty. The star is l’étoile flamboyante, which appears in Masonic symbolism, but has been confused therein. That which the figure communicates to the living scene is the substance of the heavens and the elements. It has been said truly that the mottoes of this card are \u2018Waters of Life freely\u2019 and \u2018Gifts of the Spirit.\u2019<br/>The summary of several tawdry explanations says that it is a card of hope. On other planes it has been certified as immortality and interior light. For the majority of prepared minds, the figure will appear as the type of Truth unveiled, glorious in undying beauty, pouring on the waters of the soul some part and measure of her priceless possession. But she is in reality the Great Mother in the Kabalistic Sephira Binah, which is supernal Understanding, who communicates to the Sephiroth that are below in the measure that they can receive her influx."
    },
    {
        "Id": 75,
        "Title": "XVIII of Trumps: \u2018The Moon\u2019",
        "Suit": "Trumps",
        "Ordinal": 18,
        "OrdinalName": "XVIII (The Moon)",
        "GenderedCard": "Non-specific",
        "Normal": "Hidden enemies, danger, calumny, darkness, terror, deception, error.",
        "Reversed": "Instability, inconstancy, silence, lesser degrees of deception and error.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg",
        "Description":"The distinction between this card and some of the conventional types is that the moon is increasing on what is called the side of mercy, to the right of the observer. It has sixteen chief and sixteen secondary rays. The card represents life of the imagination apart from life of the spirit. The path between the towers is the issue into the unknown. The dog and wolf are the fears of the natural mind in the presence of that place of exit, when there is only reflected light to guide it.<br/>The last reference is a key to another form of symbolism. The intellectual light is a reflection and beyond it is the unknown mystery which it cannot shew forth. It illuminates our animal nature, types of which are represented below&#8212;the dog, the wolf and that which comes up out of the deeps, the nameless and hideous tendency which is lower than the savage beast. It strives to attain manifestation, symbolized by crawling from the abyss of water to the land, but as a rule it sinks back whence it came. The face of the mind directs a calm gaze upon the unrest below; the dew of thought falls; the message is: Peace, be still; and it may be that there shall come a calm upon the animal nature, while the abyss beneath shall cease from giving up a form."
    },
    {
        "Id": 76,
        "Title": "XIX of Trumps: \u2018The Sun\u2019",
        "Suit": "Trumps",
        "Ordinal": 19,
        "OrdinalName": "XIX (The Sun)",
        "GenderedCard": "Non-specific",
        "Normal": "Material happiness, fortunate marriage, contentment.",
        "Reversed": "The same in a lesser sense.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg",
        "Description":"The naked child mounted on a white horse and displaying a red standard has been mentioned already as the better symbolism connected with this card. It is the destiny of the Supernatural East and the great and holy light which goes before the endless procession of humanity, coming out from the walled garden of the sensitive life and passing on the journey home. The card signifies, therefore, the transit from the manifest light of this world, represented by the glorious sun of earth, to the light of the world to come, which goes before aspiration and is typified by the heart of a child.<br/>But the last allusion is again the key to a different form or aspect of the symbolism. The sun is that of consciousness in the spirit - the direct as the antithesis of the reflected light. The characteristic type of humanity has become a little child therein&#8212;a child in the sense of simplicity and innocence in the sense of wisdom. In that simplicity, he bears the seal of Nature and of Art; in that innocence, he signifies the restored world. When the self-knowing spirit has dawned in the consciousness above the natural mind, that mind in its renewal leads forth the animal nature in a state of perfect conformity."
    },
    {
        "Id": 77,
        "Title": "XX of Trumps: \u2018Judgement\u2019",
        "Suit": "Trumps",
        "Ordinal": 20,
        "OrdinalName": "XX (Judgement)",
        "GenderedCard": "Non-specific",
        "Normal": "Change of position, renewal, outcome.",
        "Reversed": "Weakness, pusillanimity, simplicity; also deliberation, decision, sentence.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg",
        "Description":"I have said that this symbol is essentially invariable in all Tarot sets, or at least the variations do not alter its character. The great angel is here encompassed by clouds, but he blows his bannered trumpet, and the cross as usual is displayed on the banner. The dead are rising from their tombs&#8212;a woman on the right, a man on the left hand, and between them their child, whose back is turned. But in this card there are more than three who are restored, and it has been thought worth while to make this variation as illustrating the insufficiency of current explanations. It should be noted that all the figures are as one in the wonder, adoration and ecstacy expressed by their attitudes. It is the card which registers the accomplishment of the great work of transformation in answer to the summons of the Supernal&#8212;which summons is heard and answered from within.<br/>Herein is the intimation of a significance which cannot well be carried further in the present place. What is that within us which does sound a trumpet and all that is lower in our nature rises in response&#8212;almost in a moment, almost in the twinkling of an eye? Let the card continue to depict, for those who can see no further, the Last judgment and the resurrection in the natural body; but let those who have inward eyes look and discover therewith. They will understand that it has been called truly in the past a card of eternal life, and for this reason it may be compared with that which passes under the name of Temperance."
    },
    {
        "Id": 78,
        "Title": "XXI of Trumps: \u2018The World\u2019",
        "Suit": "Trumps",
        "Ordinal": 21,
        "OrdinalName": "XXI (The World)",
        "GenderedCard": "Female",
        "Normal": "Assured success, voyage, route, emigration, flight, change of place.",
        "Reversed": "Inertia, fixity, stagnation, permanence.",
        "Image":"https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg",
		"Description":"As this final message of the Major Trumps is unchanged&#8212;and indeed unchangeable&#8212;in respect of its design, it has been partly described already regarding its deeper sense. It represents also the perfection and end of the Cosmos, the secret which is within it, the rapture of the universe when it understands itself in God. It is further the state of the soul in the consciousness of Divine Vision, reflected from the self-knowing spirit. But these meanings are without prejudice to that which I have said concerning it on the material side.<br/>It has more than one message on the macrocosmic side and is, for example, the state of the restored world when the law of manifestation shall have been carried to the highest degree of natural perfection. But it is perhaps more especially a story of the past, referring to that day when all was declared to be good, when the morning stars sang together and all the Sons of God shouted for joy. One of the worst explanations concerning it is that the figure symbolizes the Magus when he has reached the highest degree of initiation; another account says that it represents the absolute, which is ridiculous. The figure has been said to stand for Truth, which is, however, more properly allocated to the seventeenth card. Lastly, it has been called the Crown of the Magi."
    }
];